[package]
name = "exports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.4"

[lib]
name = "exports"
path = "src/exports.rs"
